apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nzbhydra2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nzbhydra2.name" . }}
    helm.sh/chart: {{ include "nzbhydra2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nzbhydra2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nzbhydra2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GID
              value: {{ .Values.nzbhydra2.gid | quote }}
            - name: UID
              value: {{ .Values.nzbhydra2.uid | quote }}
            - name: SERVER_MODE
              value: {{ .Values.nzbhydra2.server_mode | quote }}
            - name: PGADMIN_SETUP_EMAIL
              value: {{ .Values.nzbhydra2.setup_email }}
            - name: PGADMIN_PORT
              value: {{ .Values.service.port | quote }}
            - name: PGADMIN_SETUP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "nzbhydra2.fullname" . }}
                  key: setup_password
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: http
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: http
          volumeMounts:
          - name: nzbhydra2-data
            mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: nzbhydra2-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "nzbhydra2.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
